help:-
    write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n'),
    write('%                                     ~General~                                        %\n'),
    write('% 1. map.            : Display map                                                     %\n'),
    write('% Legend             : M: Marketplace, R: Ranch H: House, Q: Quest                     %\n'),
    write('% Legend             : o: waterTile, =:diggedTile, #: border, -: grassTile             %\n'),
    write('% 2. status.         : menampilkan kondisimu terkini                                   %\n'),
    write('% 3. time.           : Check the current Day, Time, Weather and Season                 %\n'),
    write('%                                    ~Exploration~                                     %\n'),
    write('% 1. w.              : gerak ke utara 1 langkah                                        %\n'),
    write('% 2. s.              : gerak ke selatan 1 langkah                                      %\n'),
    write('% 3. d.              : gerak ke ke timur 1 langkah                                     %\n'),
    write('% 4. a.              : gerak ke barat 1 langkah                                        %\n'),
    write('% 5. house.          : Go inside your house (iff you are in house tile)                %\n'),
    write('% 6. quest.          : Check the questboard (iff you are in quest tile)                %\n'),
    write('% 7. ranch.          : Go to your ranch and start ranching (iff you are in ranch tile) %\n'),
    write('% 8. market.         : Go to market place to buy items (iff you are in market tile)    %\n'),
    write('%                                    ~Inventory~                                       %\n'),
    write('% 1. inventory.      : Display your inventory                                          %\n'),
    write('% 2. throwItem.      : Throw one or more item from your inventory                      %\n'),
    write('% 3. use.            : Use item in your inventory                                      %\n'),
    write('%                                    ~Farming~                                         %\n'),
    write('% 1. dig.            : dig tiles to start planting (iff you are in grasTile)           %\n'),
    write('% 2. plant.          : Plant crops in your inventory (iff you are in diggedTile)       %\n'),
    write('% 3. harvest.        : Plant crops in your inventory (iff you are in diggedTile)       %\n'),
    write('% 4. water.          : Water the plant to stay hydrated                                %\n'),
    write('%                                    ~Fishing~                                         %\n'),
    write('% 1. fish.           : Start fishing (iff you are in waterTile)                        %\n'),
    write('%                                    ~Ranching~                                        %\n'),
    write('% 1. chicken.        : Start budidaya chicken                                          %\n'),
    write('% 2. sheep.          : Start budidaya sheep                                            %\n'),
    write('% 3. cow.            : Start budidaya cow                                              %\n'),
    write('% 3. cow.            : Start budidaya cow                                              %\n'),
    write('%                                    ~Marketplace~                                     %\n'),
    write('% 1. buy.           : buy items from the market place                                  %\n'),
    write('% 2. sell.          : sell items from your inventory                                   %\n'),
    write('%                                    ~House~                                           %\n'),
    write('% 1. sleep.          : Sleep to restore your stamina                                   %\n'),
    write('% 2. writeDiary.     : write into your diary                                           %\n'),
    write('% 3. readDiary.      : read diary from your diary                                      %\n'),
    write('% 4. exit.           : Exit house                                                      %\n'),
    write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n'),
    write('PENTING!!! Akhiri semua perintah atau inputmu dengan titik (.)\n'), !.